module.exports = {
  VERSION: '1.0.0',
  Approvals: {
    raw: {
      abi: [
        { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'uint256',
              name: 'id',
              type: 'uint256',
            },
          ],
          name: 'LogAddApproval',
          type: 'event',
          signature:
            '0x61de8089da76c0c5634ac2626f3aee8545429a65a985d03eae4b60ca94915089',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'uint256',
              name: 'id',
              type: 'uint256',
            },
          ],
          name: 'LogRemoveApproval',
          type: 'event',
          signature:
            '0x8360f2836886d8f0e4e37847128c7754404bf85f21dc6f134e5a8595b95c4cfd',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'uint256',
              name: 'id',
              type: 'uint256',
            },
          ],
          name: 'LogSetApprovalOwnerStatus',
          type: 'event',
          signature:
            '0x2d2cf9aade20017068fdfcc5d853d460e3fdb090bc7154904e2f5d54d8b8fcd4',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
          ],
          name: 'RoleGranted',
          type: 'event',
          signature:
            '0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
          ],
          name: 'RoleRevoked',
          type: 'event',
          signature:
            '0xf6391f5c32d9c69d2a47ea670b442974b53935d1edc7fd64eb21e047a839171b',
        },
        {
          inputs: [],
          name: 'ADMIN',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x2a0acc6a',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xa217fddf',
        },
        {
          inputs: [],
          name: 'EDITOR',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x9e8d31d5',
        },
        {
          inputs: [],
          name: 'approvalCount',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x6884d0a6',
        },
        {
          inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          name: 'approvalSignerCount',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x7ccd6a95',
        },
        {
          inputs: [
            { internalType: 'uint256', name: '', type: 'uint256' },
            { internalType: 'address', name: '', type: 'address' },
          ],
          name: 'approvals',
          outputs: [
            { internalType: 'address', name: 'signer', type: 'address' },
            { internalType: 'uint256', name: 'signedStatus', type: 'uint256' },
            { internalType: 'uint256', name: 'limitAmount', type: 'uint256' },
            { internalType: 'uint256', name: 'minSigners', type: 'uint256' },
          ],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xab2850da',
        },
        {
          inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          name: 'closedApprovals',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x2849132b',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x248a9ca3',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'uint256', name: 'index', type: 'uint256' },
          ],
          name: 'getRoleMember',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x9010d07c',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleMemberCount',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xca15c873',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x2f2ff15d',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x91d14854',
        },
        {
          inputs: [],
          name: 'owner',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x8da5cb5b',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x36568abe',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xd547741f',
        },
        {
          inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          name: 'signerMapping',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x7b9249cb',
        },
        {
          inputs: [
            { internalType: 'address', name: 'sender', type: 'address' },
            { internalType: 'address[]', name: 'signers', type: 'address[]' },
            {
              internalType: 'uint256[]',
              name: 'limitAmount',
              type: 'uint256[]',
            },
            {
              internalType: 'uint256',
              name: 'minSignersCount',
              type: 'uint256',
            },
          ],
          name: 'add',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xf454bd50',
        },
        {
          inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
          name: 'remove',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x4cc82215',
        },
        {
          inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
          name: 'has',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xcccf7a8e',
        },
        {
          inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
          name: 'getSignersCount',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x28ced8df',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'id', type: 'uint256' },
            { internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'canExec',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x038d9ad7',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'id', type: 'uint256' },
            { internalType: 'address', name: 'sender', type: 'address' },
            { internalType: 'bytes', name: 'data', type: 'bytes' },
          ],
          name: 'executeExtension',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x5e311b5e',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'id', type: 'uint256' },
            { internalType: 'address', name: 'sender', type: 'address' },
            {
              internalType: 'uint256',
              name: 'amountRequested',
              type: 'uint256',
            },
          ],
          name: 'setApproved',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x043a6700',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'id', type: 'uint256' },
            { internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'canApproved',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xbe7d5ca7',
        },
        {
          inputs: [
            { internalType: 'address', name: 'user', type: 'address' },
            { internalType: 'uint8', name: 'aclType', type: 'uint8' },
          ],
          name: 'addACL',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xfe8e980b',
        },
        {
          inputs: [
            { internalType: 'address', name: 'user', type: 'address' },
            { internalType: 'uint8', name: 'aclType', type: 'uint8' },
          ],
          name: 'removeACL',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xd1e5dbc2',
        },
      ],
    },
    address: {
      development: '0x28B0F14a5A4A9C5c483c23f7ac7337785bDe72d3',
      test: '0x75Ae2bA8178a6B2e651D5D7F617DA66Aba269Beb',
      ropsten: '0x7740A63CF6FC3827589861f7D3a1Ca6307a59480',
    },
  },
  TestDocumentModel: {
    raw: {
      abi: [
        {
          inputs: [{ internalType: 'address', name: 'r', type: 'address' }],
          stateMutability: 'nonpayable',
          type: 'constructor',
          signature: 'constructor',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'uint256',
              name: 'id',
              type: 'uint256',
            },
          ],
          name: 'LogAddExtEvent',
          type: 'event',
          signature:
            '0xcc479190c541756bd832f14e89fecfd8578ccb61be7037f89583d78f11577764',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'uint256',
              name: 'current',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'next',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'fork',
              type: 'uint256',
            },
          ],
          name: 'LogExtensionEnd',
          type: 'event',
          signature:
            '0xde57c44e477e4295cdb310d1464dd9dde92407a028ac6afce81abe17fe10b1de',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'uint256',
              name: 'current',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'next',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'fork',
              type: 'uint256',
            },
          ],
          name: 'LogExtensionStart',
          type: 'event',
          signature:
            '0x3621944ade0145211aca764f848e91778f093696a3c97d90d1eb263f073f1d6f',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'address',
              name: 'recipient',
              type: 'address',
            },
            {
              indexed: true,
              internalType: 'uint256',
              name: 'next',
              type: 'uint256',
            },
            {
              indexed: true,
              internalType: 'uint256',
              name: 'actorId',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'documentId',
              type: 'uint256',
            },
          ],
          name: 'LogWorkflowStepCompleted',
          type: 'event',
          signature:
            '0xdf549a4efbe29e86cdb2cda1adac7e7b787c5e57cda0917ca6ba7134ac3d2829',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
            {
              indexed: true,
              internalType: 'uint256',
              name: 'current',
              type: 'uint256',
            },
            {
              indexed: true,
              internalType: 'uint256',
              name: 'actorId',
              type: 'uint256',
            },
          ],
          name: 'LogWorkflowStepStart',
          type: 'event',
          signature:
            '0x3c53e20059c8daa512f9d5e52ffc55e286a99e8aeb70371872191d2da39cac96',
        },
        {
          inputs: [
            { internalType: 'string', name: 'name', type: 'string' },
            { internalType: 'address', name: 'caller', type: 'address' },
            { internalType: 'uint256', name: 'id', type: 'uint256' },
          ],
          name: 'add',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xff03cf4f',
        },
        {
          inputs: [],
          name: 'currentDocumentIndex',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x3b5b4449',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'extid', type: 'uint256' },
            { internalType: 'uint256', name: 'id', type: 'uint256' },
          ],
          name: 'edit',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x53b619a3',
        },
        {
          inputs: [],
          name: 'getCurrentModelIndex',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xeb11ea2c',
        },
        {
          inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
          name: 'getStep',
          outputs: [
            {
              components: [
                {
                  internalType: 'uint256',
                  name: 'currentActor',
                  type: 'uint256',
                },
                { internalType: 'uint256', name: 'current', type: 'uint256' },
                { internalType: 'uint256', name: 'next', type: 'uint256' },
                { internalType: 'uint256', name: 'forkId', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'mappingType',
                  type: 'uint256',
                },
                {
                  internalType: 'address[]',
                  name: 'recipientValidations',
                  type: 'address[]',
                },
                {
                  internalType: 'address[]',
                  name: 'senderValidations',
                  type: 'address[]',
                },
                {
                  internalType: 'uint256[]',
                  name: 'stepValidations',
                  type: 'uint256[]',
                },
              ],
              internalType: 'struct LibWStep.WStep',
              name: '',
              type: 'tuple',
            },
          ],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x7874888a',
        },
        {
          inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
          name: 'has',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xcccf7a8e',
        },
        {
          inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
          name: 'read',
          outputs: [
            {
              components: [
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'address',
                  name: 'extContract',
                  type: 'address',
                },
                { internalType: 'string', name: 'name', type: 'string' },
              ],
              internalType: 'struct ExtensionEventRegistry.ExtEventEntry',
              name: '',
              type: 'tuple',
            },
          ],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xed2e5a97',
        },
        {
          inputs: [],
          name: 'rowCount',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x46d4294d',
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: 'uint256',
                  name: 'currentActor',
                  type: 'uint256',
                },
                { internalType: 'uint256', name: 'current', type: 'uint256' },
                { internalType: 'uint256', name: 'next', type: 'uint256' },
                { internalType: 'uint256', name: 'forkId', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'mappingType',
                  type: 'uint256',
                },
                {
                  internalType: 'address[]',
                  name: 'recipientValidations',
                  type: 'address[]',
                },
                {
                  internalType: 'address[]',
                  name: 'senderValidations',
                  type: 'address[]',
                },
                {
                  internalType: 'uint256[]',
                  name: 'stepValidations',
                  type: 'uint256[]',
                },
              ],
              internalType: 'struct LibWStep.WStep',
              name: 'step',
              type: 'tuple',
            },
            { internalType: 'uint256', name: 'index', type: 'uint256' },
          ],
          name: 'setStep',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x5e5c85a4',
        },
        {
          inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          name: 'stepsByInitState',
          outputs: [
            { internalType: 'uint256', name: 'currentActor', type: 'uint256' },
            { internalType: 'uint256', name: 'current', type: 'uint256' },
            { internalType: 'uint256', name: 'next', type: 'uint256' },
            { internalType: 'uint256', name: 'forkId', type: 'uint256' },
            { internalType: 'uint256', name: 'mappingType', type: 'uint256' },
          ],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xd52cd8e6',
        },
        {
          inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          name: 'table',
          outputs: [
            { internalType: 'string', name: 'fileIpfsJson', type: 'string' },
            {
              internalType: 'string',
              name: 'certifiedFilesIpfsJson',
              type: 'string',
            },
            { internalType: 'string', name: 'email', type: 'string' },
            { internalType: 'string', name: 'description', type: 'string' },
            { internalType: 'string', name: 'name', type: 'string' },
            { internalType: 'string', name: 'lastname', type: 'string' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
            { internalType: 'address', name: 'user', type: 'address' },
            { internalType: 'address', name: 'recipient', type: 'address' },
            { internalType: 'bytes32', name: 'status', type: 'bytes32' },
          ],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xbafff8c0',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'next', type: 'uint256' },
            { internalType: 'address', name: 'recipient', type: 'address' },
          ],
          name: 'validateRecipient',
          outputs: [],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x455e3026',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'next', type: 'uint256' },
            { internalType: 'address', name: 'sender', type: 'address' },
          ],
          name: 'validateSender',
          outputs: [],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xa25e6c51',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'next', type: 'uint256' },
            { internalType: 'uint256', name: 'status', type: 'uint256' },
          ],
          name: 'validateStatus',
          outputs: [],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x9fef77e5',
        },
        {
          inputs: [{ internalType: 'bytes', name: 'data', type: 'bytes' }],
          name: 'getStructAsTuple',
          outputs: [
            { internalType: 'string', name: '', type: 'string' },
            { internalType: 'string', name: '', type: 'string' },
            { internalType: 'string', name: '', type: 'string' },
            { internalType: 'string', name: '', type: 'string' },
            { internalType: 'string', name: '', type: 'string' },
            { internalType: 'string', name: '', type: 'string' },
            { internalType: 'uint256', name: '', type: 'uint256' },
          ],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x5bdeb08c',
        },
        {
          inputs: [{ internalType: 'bytes', name: 'data', type: 'bytes' }],
          name: 'getStruct',
          outputs: [
            {
              components: [
                {
                  internalType: 'string',
                  name: 'fileIpfsJson',
                  type: 'string',
                },
                {
                  internalType: 'string',
                  name: 'certifiedFilesIpfsJson',
                  type: 'string',
                },
                { internalType: 'string', name: 'email', type: 'string' },
                { internalType: 'string', name: 'description', type: 'string' },
                { internalType: 'string', name: 'name', type: 'string' },
                { internalType: 'string', name: 'lastname', type: 'string' },
                { internalType: 'uint256', name: 'amount', type: 'uint256' },
                { internalType: 'address', name: 'user', type: 'address' },
                { internalType: 'address', name: 'recipient', type: 'address' },
                { internalType: 'bytes32', name: 'status', type: 'bytes32' },
              ],
              internalType: 'struct TestDocumentModel.TestDocument',
              name: '',
              type: 'tuple',
            },
          ],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x16e4504c',
        },
        {
          inputs: [
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'address', name: 'sender', type: 'address' },
            { internalType: 'uint256', name: 'next', type: 'uint256' },
            { internalType: 'uint256', name: 'current', type: 'uint256' },
            { internalType: 'bytes', name: 'fields', type: 'bytes' },
          ],
          name: 'onAddRow',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xe0cfbde8',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'doc', type: 'uint256' },
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'address', name: 'sender', type: 'address' },
            { internalType: 'uint256', name: 'next', type: 'uint256' },
            { internalType: 'uint256', name: 'current', type: 'uint256' },
            {
              components: [
                {
                  internalType: 'string',
                  name: 'fileIpfsJson',
                  type: 'string',
                },
                {
                  internalType: 'string',
                  name: 'certifiedFilesIpfsJson',
                  type: 'string',
                },
                { internalType: 'string', name: 'email', type: 'string' },
                { internalType: 'string', name: 'description', type: 'string' },
                { internalType: 'string', name: 'name', type: 'string' },
                { internalType: 'string', name: 'lastname', type: 'string' },
                { internalType: 'uint256', name: 'amount', type: 'uint256' },
                { internalType: 'address', name: 'user', type: 'address' },
                { internalType: 'address', name: 'recipient', type: 'address' },
                { internalType: 'bytes32', name: 'status', type: 'bytes32' },
              ],
              internalType: 'struct TestDocumentModel.TestDocument',
              name: 'document',
              type: 'tuple',
            },
          ],
          name: 'onUpdate',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xb3e36c69',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'doc', type: 'uint256' },
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'address', name: 'sender', type: 'address' },
            { internalType: 'uint256', name: 'next', type: 'uint256' },
            { internalType: 'uint256', name: 'current', type: 'uint256' },
            {
              internalType: 'uint256',
              name: 'extensionEvtId',
              type: 'uint256',
            },
            {
              components: [
                {
                  internalType: 'string',
                  name: 'fileIpfsJson',
                  type: 'string',
                },
                {
                  internalType: 'string',
                  name: 'certifiedFilesIpfsJson',
                  type: 'string',
                },
                { internalType: 'string', name: 'email', type: 'string' },
                { internalType: 'string', name: 'description', type: 'string' },
                { internalType: 'string', name: 'name', type: 'string' },
                { internalType: 'string', name: 'lastname', type: 'string' },
                { internalType: 'uint256', name: 'amount', type: 'uint256' },
                { internalType: 'address', name: 'user', type: 'address' },
                { internalType: 'address', name: 'recipient', type: 'address' },
                { internalType: 'bytes32', name: 'status', type: 'bytes32' },
              ],
              internalType: 'struct TestDocumentModel.TestDocument',
              name: 'document',
              type: 'tuple',
            },
          ],
          name: 'onExtensionUpdate',
          outputs: [
            { internalType: 'bool', name: '', type: 'bool' },
            { internalType: 'uint256', name: '', type: 'uint256' },
          ],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x56c82330',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'doc', type: 'uint256' },
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'address', name: 'sender', type: 'address' },
            { internalType: 'uint256', name: 'next', type: 'uint256' },
            { internalType: 'uint256', name: 'current', type: 'uint256' },
            {
              internalType: 'uint256',
              name: 'extensionEvtId',
              type: 'uint256',
            },
            { internalType: 'bytes', name: 'fields', type: 'bytes' },
          ],
          name: 'updateSwitch',
          outputs: [
            { internalType: 'bool', name: '', type: 'bool' },
            { internalType: 'uint256', name: '', type: 'uint256' },
          ],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xd7ddb99a',
        },
      ],
    },
    address: {
      development: '0x2427AF9aEa4E3a643aB566f6A2a6a42DEF50EB09',
      test: '0xfA994Ecd7A68E4402836BfA550dE186CcFC04Bf7',
      ropsten: '0x052c81A318B46fEDbEF4CbE0b19d23f26756ad72',
    },
  },
  ExtensionEventRegistry: {
    raw: {
      abi: [
        { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'uint256',
              name: 'id',
              type: 'uint256',
            },
          ],
          name: 'LogAddExtEvent',
          type: 'event',
          signature:
            '0xcc479190c541756bd832f14e89fecfd8578ccb61be7037f89583d78f11577764',
        },
        {
          inputs: [
            { internalType: 'string', name: 'name', type: 'string' },
            { internalType: 'address', name: 'caller', type: 'address' },
            { internalType: 'uint256', name: 'id', type: 'uint256' },
          ],
          name: 'add',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xff03cf4f',
        },
        {
          inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
          name: 'has',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xcccf7a8e',
        },
        {
          inputs: [
            { internalType: 'uint256', name: 'extid', type: 'uint256' },
            { internalType: 'uint256', name: 'id', type: 'uint256' },
          ],
          name: 'edit',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x53b619a3',
        },
        {
          inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
          name: 'read',
          outputs: [
            {
              components: [
                { internalType: 'uint256', name: 'id', type: 'uint256' },
                {
                  internalType: 'address',
                  name: 'extContract',
                  type: 'address',
                },
                { internalType: 'string', name: 'name', type: 'string' },
              ],
              internalType: 'struct ExtensionEventRegistry.ExtEventEntry',
              name: '',
              type: 'tuple',
            },
          ],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xed2e5a97',
        },
      ],
    },
    address: {
      development: '0x469b94A497f05226b57163F8ffF2Ac5A7d50990E',
      test: '0xD18aC5f8d6a1A76d795248b938ed16BEC5c75ea6',
      ropsten: '0xfA72D80472b10e5f315e8f9d4652C0f8d3E31EE7',
    },
  },
  WTemplate: {
    raw: {
      abi: [
        {
          inputs: [
            { internalType: 'address', name: '_owner', type: 'address' },
            { internalType: 'address', name: '_model', type: 'address' },
          ],
          stateMutability: 'nonpayable',
          type: 'constructor',
          signature: 'constructor',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'address',
              name: 'id',
              type: 'address',
            },
          ],
          name: 'LogIdentityAdded',
          type: 'event',
          signature:
            '0x96a67e602614398240312075d810102f6156834a598faf543f8e2c2e4cecb6b8',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'string',
              name: 'key',
              type: 'string',
            },
          ],
          name: 'LogLicenseCreated',
          type: 'event',
          signature:
            '0xfc3966531ddfc7ad6471ad015ece52c51c98e90489678b1bbf591d83bde5305d',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'string',
              name: 'apiKey',
              type: 'string',
            },
          ],
          name: 'LogLicenseEnabled',
          type: 'event',
          signature:
            '0x3689df2dacc9584137727ef65fb091dafebdcd0719897d70d6d406dc2fbb67c0',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: 'string',
              name: 'apiKey',
              type: 'string',
            },
          ],
          name: 'LogLicenseRenewed',
          type: 'event',
          signature:
            '0xdb1cc5669b3841d305deef2d9fa8290cdfa4a0234d67a25f0cfa7db0ebd1bbda',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'address',
              name: 'recipient',
              type: 'address',
            },
            {
              indexed: true,
              internalType: 'uint256',
              name: 'next',
              type: 'uint256',
            },
            {
              indexed: true,
              internalType: 'uint256',
              name: 'actorId',
              type: 'uint256',
            },
            {
              indexed: false,
              internalType: 'uint256',
              name: 'documentId',
              type: 'uint256',
            },
          ],
          name: 'LogWorkflowStepCompleted',
          type: 'event',
          signature:
            '0xdf549a4efbe29e86cdb2cda1adac7e7b787c5e57cda0917ca6ba7134ac3d2829',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
            {
              indexed: true,
              internalType: 'uint256',
              name: 'current',
              type: 'uint256',
            },
            {
              indexed: true,
              internalType: 'uint256',
              name: 'actorId',
              type: 'uint256',
            },
          ],
          name: 'LogWorkflowStepStart',
          type: 'event',
          signature:
            '0x3c53e20059c8daa512f9d5e52ffc55e286a99e8aeb70371872191d2da39cac96',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
          ],
          name: 'RoleGranted',
          type: 'event',
          signature:
            '0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d',
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: 'bytes32',
              name: 'role',
              type: 'bytes32',
            },
            {
              indexed: true,
              internalType: 'address',
              name: 'account',
              type: 'address',
            },
            {
              indexed: true,
              internalType: 'address',
              name: 'sender',
              type: 'address',
            },
          ],
          name: 'RoleRevoked',
          type: 'event',
          signature:
            '0xf6391f5c32d9c69d2a47ea670b442974b53935d1edc7fd64eb21e047a839171b',
        },
        {
          inputs: [],
          name: 'ADMIN',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x2a0acc6a',
        },
        {
          inputs: [],
          name: 'DEFAULT_ADMIN_ROLE',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xa217fddf',
        },
        {
          inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
          name: 'addACL',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x84e5ddcb',
        },
        {
          inputs: [
            { internalType: 'address', name: 'id', type: 'address' },
            { internalType: 'string', name: 'did', type: 'string' },
            { internalType: 'string', name: 'key', type: 'string' },
          ],
          name: 'addIdentity',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x9eaa8154',
        },
        {
          inputs: [
            { internalType: 'string', name: 'key', type: 'string' },
            { internalType: 'uint256', name: 'expires', type: 'uint256' },
            { internalType: 'string', name: 'description', type: 'string' },
          ],
          name: 'createLicense',
          outputs: [{ internalType: 'string', name: '', type: 'string' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x52424da3',
        },
        {
          inputs: [
            { internalType: 'uint256', name: '', type: 'uint256' },
            { internalType: 'uint256', name: '', type: 'uint256' },
          ],
          name: 'findNext',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x7cd3262b',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleAdmin',
          outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x248a9ca3',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'uint256', name: 'index', type: 'uint256' },
          ],
          name: 'getRoleMember',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x9010d07c',
        },
        {
          inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
          name: 'getRoleMemberCount',
          outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xca15c873',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
          ],
          name: 'grantRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x2f2ff15d',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
          ],
          name: 'hasRole',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x91d14854',
        },
        {
          inputs: [{ internalType: 'address', name: 'admin', type: 'address' }],
          name: 'isAdmin',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x24d7806c',
        },
        {
          inputs: [{ internalType: 'string', name: '', type: 'string' }],
          name: 'licenses',
          outputs: [
            { internalType: 'uint256', name: 'expires', type: 'uint256' },
            { internalType: 'string', name: 'description', type: 'string' },
            { internalType: 'bool', name: 'enabled', type: 'bool' },
            { internalType: 'bool', name: 'created', type: 'bool' },
            { internalType: 'string', name: 'did', type: 'string' },
          ],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x0540dafd',
        },
        {
          inputs: [],
          name: 'owner',
          outputs: [{ internalType: 'address', name: '', type: 'address' }],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x8da5cb5b',
        },
        {
          inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
          name: 'removeACL',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x98b91446',
        },
        {
          inputs: [
            { internalType: 'address', name: 'id', type: 'address' },
            { internalType: 'string', name: 'key', type: 'string' },
            { internalType: 'uint256', name: 'expires', type: 'uint256' },
          ],
          name: 'renewLicense',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x6fea761d',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
          ],
          name: 'renounceRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x36568abe',
        },
        {
          inputs: [
            { internalType: 'bytes32', name: 'role', type: 'bytes32' },
            { internalType: 'address', name: 'account', type: 'address' },
          ],
          name: 'revokeRole',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xd547741f',
        },
        {
          inputs: [],
          name: 'userCount',
          outputs: [
            { internalType: 'uint256', name: '_value', type: 'uint256' },
          ],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0x07973ccf',
        },
        {
          inputs: [{ internalType: 'address', name: '', type: 'address' }],
          name: 'users',
          outputs: [
            { internalType: 'uint256', name: 'expires', type: 'uint256' },
            { internalType: 'string', name: 'description', type: 'string' },
            { internalType: 'bool', name: 'enabled', type: 'bool' },
            { internalType: 'bool', name: 'created', type: 'bool' },
            { internalType: 'string', name: 'did', type: 'string' },
          ],
          stateMutability: 'view',
          type: 'function',
          constant: true,
          signature: '0xa87430ba',
        },
        {
          inputs: [
            { internalType: 'bytes[]', name: '_actorActions', type: 'bytes[]' },
            {
              components: [
                {
                  internalType: 'uint256',
                  name: 'currentActor',
                  type: 'uint256',
                },
                { internalType: 'uint256', name: 'current', type: 'uint256' },
                { internalType: 'uint256', name: 'next', type: 'uint256' },
                { internalType: 'uint256', name: 'forkId', type: 'uint256' },
                {
                  internalType: 'uint256',
                  name: 'mappingType',
                  type: 'uint256',
                },
                {
                  internalType: 'address[]',
                  name: 'recipientValidations',
                  type: 'address[]',
                },
                {
                  internalType: 'address[]',
                  name: 'senderValidations',
                  type: 'address[]',
                },
                {
                  internalType: 'uint256[]',
                  name: 'stepValidations',
                  type: 'uint256[]',
                },
              ],
              internalType: 'struct LibWStep.WStep[]',
              name: '_steps',
              type: 'tuple[]',
            },
          ],
          name: 'createWF',
          outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0x096f2cda',
        },
        {
          inputs: [
            { internalType: 'address', name: 'to', type: 'address' },
            { internalType: 'uint256', name: 'step', type: 'uint256' },
            { internalType: 'uint256', name: 'actor', type: 'uint256' },
            { internalType: 'uint256', name: 'docId', type: 'uint256' },
            { internalType: 'uint256', name: 'extid', type: 'uint256' },
            { internalType: 'bytes', name: 'payload', type: 'bytes' },
          ],
          name: 'executeStep',
          outputs: [],
          stateMutability: 'nonpayable',
          type: 'function',
          signature: '0xeb219a9d',
        },
      ],
    },
    address: {
      development: '0xa929aC9F628F6B0eD60268D52dc66fE96db897E2',
      test: '0xCB4B9Cf8fe72a08D6Abb7B0E806b974a6535753F',
      ropsten: '0x82f22A2bf1741fD83850ffd79F2bd82fcC5863BD',
    },
  },
};
